name: atlite_wind_speeds
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - pandas
  - matplotlib
  - numpy
  - pygadm
  - jupyter
  - ipython
  - ipykernel
  - atlite
  - logging
  - hvplot
  - holoviews
  - cartopy
  - xarray

